--autogenerated stuff
CREATE TABLE if not exists area
(
    id   BIGINT NOT NULL,
    name TEXT,
    CONSTRAINT pk_area PRIMARY KEY (id)
);

CREATE TABLE if not exists favorite_employer
(
    id          BIGINT NOT NULL,
    name        TEXT,
    date_create TIMESTAMP WITHOUT TIME ZONE,
    area_id     BIGINT NOT NULL,
    comment     TEXT,
    popularity  VARCHAR(255),
    views_count INTEGER,
    description TEXT,
    CONSTRAINT pk_favorite_employer PRIMARY KEY (id),
    CONSTRAINT FK_FAVORITE_EMPLOYER_ON_AREA FOREIGN KEY (area_id) REFERENCES area (id)
);

CREATE TABLE if not exists favorite_vacancy
(
    id          BIGINT NOT NULL,
    name        TEXT,
    date_create TIMESTAMP WITHOUT TIME ZONE,
    area_id     BIGINT NOT NULL,
    comment     TEXT,
    popularity  VARCHAR(255),
    views_count INTEGER,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    employer_id BIGINT,
    salary_from DECIMAL,
    salary_to   DECIMAL,
    currency    VARCHAR(255),
    gross       BOOLEAN,
    CONSTRAINT pk_favorite_vacancy PRIMARY KEY (id),
    CONSTRAINT FK_FAVORITE_VACANCY_ON_AREA FOREIGN KEY (area_id) REFERENCES area (id),
    CONSTRAINT FK_FAVORITE_VACANCY_ON_EMPLOYER FOREIGN KEY (employer_id) REFERENCES favorite_employer (id)
);
